[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[build]
  base = "url-shortener-frontend"
  command = "npm run build"
  publish = "dist"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Short URL redirects
[[redirects]]
  from = "/:shortId"
  to = "https://url-shortener-app-q188.onrender.com/:shortId"
  status = 302
  force = true
